CREATE TABLE TwitterAccounts (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,
    EncryptedStorageState MEDIUMTEXT NULL,
    SessionStatus VARCHAR(20) NOT NULL DEFAULT 'DISCONNECTED',
    LastLoginAt DATETIME(3) NULL,
    LastError VARCHAR(1000) NULL,
    CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (Id),
    UNIQUE KEY UK_TwitterAccounts_Username (Username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TwitterPosts (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    AccountId BIGINT NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    TweetUrl VARCHAR(500) NULL,
    ErrorMessage VARCHAR(2000) NULL,
    AttemptCount INT NOT NULL DEFAULT 0,
    SentAt DATETIME(3) NULL,
    CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (Id),
    KEY IX_TwitterPosts_Account_Status_Created (AccountId, Status, CreatedAt),
    CONSTRAINT FK_TwitterPosts_Account FOREIGN KEY (AccountId) REFERENCES TwitterAccounts(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TwitterPostMedia (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    PostId BIGINT NOT NULL,
    StoragePath VARCHAR(1000) NOT NULL,
    OriginalFileName VARCHAR(255) NOT NULL,
    ContentType VARCHAR(100) NOT NULL,
    FileSize BIGINT NOT NULL,
    Sha256 CHAR(64) NOT NULL,
    SortOrder INT NOT NULL,
    CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (Id),
    KEY IX_TwitterPostMedia_Post_Sort (PostId, SortOrder),
    CONSTRAINT FK_TwitterPostMedia_Post FOREIGN KEY (PostId) REFERENCES TwitterPosts(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
