CREATE TABLE GeneratedAssets (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    Platform VARCHAR(20) NOT NULL,
    PathHash CHAR(64) NOT NULL,
    LocalPath VARCHAR(2000) NOT NULL,
    LocalUrl VARCHAR(2500) NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    FileSize BIGINT NOT NULL DEFAULT 0,
    Width INT NULL,
    Height INT NULL,
    Prompt TEXT NULL,
    NegativePrompt TEXT NULL,
    Seed BIGINT NULL,
    Steps INT NULL,
    Cfg DOUBLE NULL,
    Sampler VARCHAR(100) NULL,
    Scheduler VARCHAR(100) NULL,
    WorkflowId VARCHAR(100) NULL,
    GeneratedAt DATETIME(3) NULL,
    CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (Id),
    UNIQUE KEY UK_GeneratedAssets_Platform_PathHash (Platform, PathHash),
    KEY IX_GeneratedAssets_Platform_CreatedAt (Platform, CreatedAt DESC)
);
