CREATE TABLE IF NOT EXISTS SyncRecords (
  Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DeviceId VARCHAR(100) NOT NULL,
  EntityType VARCHAR(100) NOT NULL,
  EntityId VARCHAR(160) NOT NULL,
  Operation VARCHAR(16) NOT NULL DEFAULT 'upsert',
  Payload JSON NOT NULL,
  SourceUpdatedAt DATETIME(6) NULL,
  SyncedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY UK_SyncRecords_Source (DeviceId, EntityType, EntityId),
  KEY IX_SyncRecords_SyncedAt (SyncedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS SyncRuns (
  Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DeviceId VARCHAR(100) NOT NULL,
  ReceivedCount INT NOT NULL,
  UpsertedCount INT NOT NULL,
  FailedCount INT NOT NULL,
  ErrorMessage VARCHAR(500) NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY IX_SyncRuns_DeviceCreated (DeviceId, CreatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
