CREATE TABLE c_LocalGeneratedImages (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    Platform VARCHAR(20) NOT NULL,
    PathHash CHAR(64) NOT NULL,
    PromptId VARCHAR(100) NOT NULL,
    ImagePath VARCHAR(2000) NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    WorkflowId VARCHAR(100) NULL,
    WorkflowName VARCHAR(255) NULL,
    Prompt TEXT NULL,
    NegativePrompt TEXT NULL,
    LorasJson TEXT NULL,
    Seed BIGINT NULL,
    Steps INT NULL,
    Cfg DOUBLE NULL,
    Sampler VARCHAR(100) NULL,
    Scheduler VARCHAR(100) NULL,
    Width INT NULL,
    Height INT NULL,
    TaskCreatedAt DATETIME(3) NULL,
    GenerationCompletedAt DATETIME(3) NULL,
    GenerationDurationMs BIGINT NULL,
    CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (Id),
    UNIQUE KEY UK_LocalGeneratedImages_Platform_PathHash (Platform, PathHash),
    KEY IX_LocalGeneratedImages_PromptId (PromptId),
    KEY IX_LocalGeneratedImages_CompletedAt (GenerationCompletedAt DESC)
);
