CREATE TABLE IF NOT EXISTS ComfyUiTasks (
  Id VARCHAR(36) NOT NULL PRIMARY KEY,
  WorkflowName VARCHAR(120) NOT NULL,
  PositivePrompt TEXT NOT NULL,
  NegativePrompt TEXT NULL,
  ParametersJson JSON NOT NULL,
  InputFile VARCHAR(500) NULL,
  OutputFile VARCHAR(500) NULL,
  OutputMime VARCHAR(100) NULL,
  Status VARCHAR(32) NOT NULL,
  Progress INT NOT NULL DEFAULT 0,
  ErrorMessage VARCHAR(1000) NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY IX_ComfyUiTasks_CreatedAt (CreatedAt),
  KEY IX_ComfyUiTasks_Status (Status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
