CREATE TABLE c_AsrTranscriptionRecords (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  RecordId VARCHAR(40) NULL,
  RequestId VARCHAR(128) NOT NULL,
  CharacterId VARCHAR(96) NOT NULL,
  CharacterNameSnapshot VARCHAR(160) NOT NULL,
  SessionId VARCHAR(128) NULL,
  AudioPath VARCHAR(1024) NOT NULL,
  AudioFormat VARCHAR(16) NOT NULL,
  AudioSize BIGINT NOT NULL,
  AudioDurationMs BIGINT NULL,
  RecognizedText LONGTEXT NULL,
  CorrectedText LONGTEXT NULL,
  Provider VARCHAR(64) NOT NULL,
  Model VARCHAR(128) NOT NULL,
  Language VARCHAR(32) NOT NULL,
  ProcessingTimeMs BIGINT NULL,
  Status VARCHAR(16) NOT NULL,
  ErrorCode VARCHAR(64) NULL,
  ErrorMessage VARCHAR(512) NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (Id),
  UNIQUE KEY UK_AsrTranscriptionRecords_RecordId (RecordId),
  UNIQUE KEY UK_AsrTranscriptionRecords_RequestId (RequestId),
  KEY IX_AsrTranscriptionRecords_CreatedAt (CreatedAt DESC),
  KEY IX_AsrTranscriptionRecords_CharacterStatus (CharacterId, Status, CreatedAt DESC),
  KEY IX_AsrTranscriptionRecords_ProviderModel (Provider, Model, CreatedAt DESC),
  CONSTRAINT CK_AsrTranscriptionRecords_Status CHECK (Status IN ('PROCESSING','SUCCESS','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
