CREATE TABLE IF NOT EXISTS ComfyUiPresets (
  Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(100) NOT NULL,
  PositivePrompt TEXT NOT NULL,
  NegativePrompt TEXT NULL,
  Seed BIGINT NOT NULL DEFAULT -1,
  Width INT NOT NULL,
  Height INT NOT NULL,
  Steps INT NOT NULL,
  Cfg DECIMAL(6,2) NOT NULL,
  Sampler VARCHAR(64) NOT NULL,
  Scheduler VARCHAR(64) NOT NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY IX_ComfyUiPresets_UpdatedAt (UpdatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
