ALTER TABLE ComfyUiPresets
  ADD COLUMN RandomSeed BOOLEAN NOT NULL DEFAULT TRUE AFTER Seed,
  ADD COLUMN ControlMode VARCHAR(32) NOT NULL DEFAULT 'openpose' AFTER Scheduler,
  ADD COLUMN StyleStrength DECIMAL(6,4) NOT NULL DEFAULT 0.45 AFTER ControlMode,
  ADD COLUMN StyleWeightType VARCHAR(64) NOT NULL DEFAULT 'style transfer (SDXL)' AFTER StyleStrength,
  ADD COLUMN StyleEndAt DECIMAL(6,4) NOT NULL DEFAULT 0.65 AFTER StyleWeightType,
  ADD COLUMN CombineEmbeds VARCHAR(32) NOT NULL DEFAULT 'average' AFTER StyleEndAt,
  ADD COLUMN OpenPoseStrength DECIMAL(6,4) NOT NULL DEFAULT 0.80 AFTER CombineEmbeds,
  ADD COLUMN DepthStrength DECIMAL(6,4) NOT NULL DEFAULT 0.40 AFTER OpenPoseStrength,
  ADD COLUMN SecondPassSteps INT NOT NULL DEFAULT 22 AFTER DepthStrength,
  ADD COLUMN SecondPassDenoise DECIMAL(6,4) NOT NULL DEFAULT 0.28 AFTER SecondPassSteps,
  ADD COLUMN FaceDetailerSteps INT NOT NULL DEFAULT 20 AFTER SecondPassDenoise,
  ADD COLUMN FaceDetailerDenoise DECIMAL(6,4) NOT NULL DEFAULT 0.30 AFTER FaceDetailerSteps;
