ALTER TABLE ComfyUiPresets
  ADD COLUMN Loras TEXT NULL AFTER NegativePrompt,
  ADD COLUMN BatchSize INT NOT NULL DEFAULT 1 AFTER Height,
  ADD COLUMN Denoise DECIMAL(6,4) NOT NULL DEFAULT 1.0 AFTER Cfg;
