package com.aiprovider.model.vo;

import java.time.LocalDateTime;

public class ContentItemVO {
    private final Long id; private final Long sourceId; private final String externalId; private final String sourceUrl; private final String authorName; private final String rawText; private final LocalDateTime publishedAt; private final String processingStatus; private final String relevanceStatus; private final java.math.BigDecimal relevanceScore; private final String relevanceReason; private final LocalDateTime relevanceCheckedAt; private final LocalDateTime collectedAt;
    public ContentItemVO(Long id,Long sourceId,String externalId,String sourceUrl,String authorName,String rawText,LocalDateTime publishedAt,String processingStatus,String relevanceStatus,java.math.BigDecimal relevanceScore,String relevanceReason,LocalDateTime relevanceCheckedAt,LocalDateTime collectedAt){this.id=id;this.sourceId=sourceId;this.externalId=externalId;this.sourceUrl=sourceUrl;this.authorName=authorName;this.rawText=rawText;this.publishedAt=publishedAt;this.processingStatus=processingStatus;this.relevanceStatus=relevanceStatus;this.relevanceScore=relevanceScore;this.relevanceReason=relevanceReason;this.relevanceCheckedAt=relevanceCheckedAt;this.collectedAt=collectedAt;}
    public Long getId(){return id;} public Long getSourceId(){return sourceId;} public String getExternalId(){return externalId;} public String getSourceUrl(){return sourceUrl;} public String getAuthorName(){return authorName;} public String getRawText(){return rawText;} public LocalDateTime getPublishedAt(){return publishedAt;} public String getProcessingStatus(){return processingStatus;} public String getRelevanceStatus(){return relevanceStatus;} public java.math.BigDecimal getRelevanceScore(){return relevanceScore;} public String getRelevanceReason(){return relevanceReason;} public LocalDateTime getRelevanceCheckedAt(){return relevanceCheckedAt;} public LocalDateTime getCollectedAt(){return collectedAt;}
}
